services:

  ollama:
    hostname: ollama
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ./entrypoint.sh:/app/entrypoint.sh
    entrypoint: ["/bin/sh", "/app/entrypoint.sh"]

  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=file'
      - 'POSTGRES_PASSWORD=pass'
      - 'POSTGRES_USER=user'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
